### ISSUE TITLE
Translation > cookie generation and ACCEPT_LANGUAGE

### ISSUE THREAD

**Issue by rodmar35** [KoboldMalade/Slim-Skeleton#2]
Hi, thanks a lot for this skeleton.

I've got some problems with translation.

For information i success by edit DetectLanguage.php this way : 
```
		public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
		{

			if (!isset($_COOKIE['language'])) {
				$serverParams = $request->getServerParams();
				setcookie(
					'language',
					substr($serverParams['HTTP_ACCEPT_LANGUAGE'], 0, 2),
					(new DateTime())->add(new DateInterval('P90D'))->format('U'),
					$this->container->get('settings')['cookies']['path'],
					$this->container->get('settings')['cookies']['domain'],
					$this->container->get('settings')['cookies']['secure'],
					$this->container->get('settings')['cookies']['httpOnly']
				);
			}
			return $handler->handle($request);
		}
```
Hope it's good.
RodMar

**Comment by KoboldMalade** [comment]
Personally I don't have any problems and the cookie is well created.

Which browser do you use?
Could I get the "Accept-Language" content from your browser? (https://aruljohn.com/language.php)

**Comment by rodmar35** [comment]
Hello, 

I're right.
Finally I success with your process function.
I just need to remove domain setting `$this->container->get('settings')['cookies']['domain'],` certainly due to my localhost development(with Valet on Mac OS).
Thanks a lot
RodMar
